services:
  db:
    image: mysql:8.0
    container_name: themis_db
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_0900_ai_ci
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p\"$MYSQL_ROOT_PASSWORD\""]
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: themis_minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console Web
    volumes:
      - minio_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: themis_app
    depends_on:
      db:
        condition: service_healthy
      # minio:
      #   condition: service_started
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - docs_gerados:/app/public/documentos/gerados
      - uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  db_data:
  docs_gerados:
  uploads:
  minio_data:
